version: "3.9"

services:
  postgres:
    image: postgres:16.2-alpine3.18
    environment:
      POSTGRES_DB: "${PG_DATABASE}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - postgres

    restart: unless-stopped
    ports:
      - "${PG_PORT}:${PG_PORT}"

    command: -p ${PG_PORT}

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:
